services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: estudo-feed
    environment:
      - MYSQL_ROOT_PASSWORD=estudofeed
      - MYSQL_DATABASE=estudo_cassandra
    ports:
      - 3307:3306
    networks:
      - estudo-feed-network

  redis:
    image: redis:latest
    container_name: feed-redis
    ports:
      - 6379:6379

  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042

  kafka:
    image: wurstmeister/kafka:latest
    container_name: feed-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181

networks:
  estudo-feed-network:

volumes:
  mysql-data:
    driver: local